#!/bin/zsh
# KevDots — Claude multi-account setup

source "$(dirname "$0")/../lib/log.sh"

setup_claude_accounts() {
  section "Claude Accounts"
  echo ""
  gum style --foreground "$GRAY" "Each account gets its own folder in ~/.claude-accounts/<name>"
  echo ""

  local count
  count=$(gum input \
    --placeholder "How many Claude accounts? (e.g. 3)" \
    --prompt "> " \
    --prompt.foreground "$PURPLE")

  if ! echo "$count" | grep -qE '^[1-9][0-9]*$'; then
    log_err "Invalid number."
    return 1
  fi

  local names=()
  local i=1
  while [ $i -le $count ]; do
    local name
    name=$(gum input \
      --placeholder "Account $i name (e.g. personal, elsol, rocketcode)" \
      --prompt "> " \
      --prompt.foreground "$PINK")

    if [ -z "$name" ]; then
      log_err "Name cannot be empty."
      continue
    fi
    names+=("$name")
    i=$((i + 1))
  done

  section "Creating folders"
  local aliases_block="# Claude accounts — generated by KevDots"
  for name in "${names[@]}"; do
    local dir="$HOME/.claude-accounts/$name"
    mkdir -p "$dir"
    [ -f "$HOME/.claude/settings.json" ]  && /bin/cp "$HOME/.claude/settings.json" "$dir/"
    [ -f "$HOME/.claude/CLAUDE.md" ]      && /bin/cp "$HOME/.claude/CLAUDE.md" "$dir/"
    [ -d "$HOME/.claude/skills" ]         && /bin/cp -r "$HOME/.claude/skills" "$dir/"
    [ -d "$HOME/.claude/output-styles" ]  && /bin/cp -r "$HOME/.claude/output-styles" "$dir/"
    log_ok "~/.claude-accounts/$name"
    aliases_block="$aliases_block
alias cl-$name='CLAUDE_CONFIG_DIR=$HOME/.claude-accounts/$name claude'
alias clogin-$name='CLAUDE_CONFIG_DIR=$HOME/.claude-accounts/$name claude auth login'"
  done

  echo ""
  section "Generated aliases"
  gum style --foreground "$GRAY" "$aliases_block"
  echo ""

  if gum confirm "Add these aliases to ~/.aliases?"; then
    printf "\n%s\n" "$aliases_block" >> ~/.aliases
    log_ok "Aliases added to ~/.aliases"
    gum style --foreground "$PINK" "  Run: source ~/.aliases"
  fi

  echo ""
  gum style --foreground "$GREEN" --padding "1 2" \
    "Accounts configured." \
    "Use 'clogin-<name>' to authenticate each one."
}
